//此文件引入内部 或外部 m-pack的公共组件 进行注册, 主要针对公用部分
import Vue from 'vue';

import mheader from '@/views/tibao/partials/header.vue';
/*import {Grid,GridItem} from '../../m-pack/src/components/grid';
import GroupTitle from '../../m-pack/src/components/group-title'
import Card from '../../m-pack/src/components/card'
import Divider from '../../m-pack/src/components/divider'*/

import Actionsheet from '../../m-pack/src1/components/actionsheet/index.vue'
import Agree from '../../m-pack/src1/components/agree/index.vue'
import AjaxPlugin from '../../m-pack/src1/plugins/ajax/index.js'
import Alert from '../../m-pack/src1/components/alert/index.vue'
import AlertModule from '../../m-pack/src1/plugins/alert/module'
import AlertPlugin from '../../m-pack/src1/plugins/alert/index.js'
import AppPlugin from '../../m-pack/src1/plugins/app/index.js'
import Array2stringFilter from '../../m-pack/src1/filters/array2String.js'
import Badge from '../../m-pack/src1/components/badge/index.vue'
import base64 from '../../m-pack/src1/tools/base64/index.js'
import Blur from '../../m-pack/src1/components/blur/index.vue'
import Box from '../../m-pack/src1/components/box/index.vue'
import BusPlugin from '../../m-pack/src1/plugins/bus/index.js'
import ButtonTab from '../../m-pack/src1/components/button-tab/button-tab.vue'
import ButtonTabItem from '../../m-pack/src1/components/button-tab/button-tab-item.vue'
import Calendar from '../../m-pack/src1/components/calendar/index.vue'
import Card from '../../m-pack/src1/components/card/index.vue'
import Cell from '../../m-pack/src1/components/cell/index.vue'
import CellBox from '../../m-pack/src1/components/cell-box/index.vue'
import CellFormPreview from '../../m-pack/src1/components/cell-form-preview/index.vue'
import Checker from '../../m-pack/src1/components/checker/checker.vue'
import CheckerItem from '../../m-pack/src1/components/checker/checker-item.vue'
import CheckIcon from '../../m-pack/src1/components/check-icon/index.vue'
import Checklist from '../../m-pack/src1/components/checklist/index.vue'
import ChinaAddressData from '../../m-pack/src1/datas/china_address.json'
import ChinaAddressV1Data from '../../m-pack/src1/datas/china_address_v1.json'
import ChinaAddressV2Data from '../../m-pack/src1/datas/china_address_v2.json'
import ChinaAddressV3Data from '../../m-pack/src1/datas/china_address_v3.json'
import ChinaAddressV4Data from '../../m-pack/src1/datas/china_address_v4.json'
import ChinamobileTool from '../../m-pack/src1/tools/validator/chinaMobile.js'
import ClickOutsideDirective from '../../m-pack/src1/directives/click-outside/index.js'
import Clocker from '../../m-pack/src1/components/clocker/index.vue'
import CloseDialogsPlugin from '../../m-pack/src1/plugins/close-dialogs/index.js'
import ColorPicker from '../../m-pack/src1/components/color-picker/index.vue'
import ConfigPlugin from '../../m-pack/src1/plugins/config/index.js'
import Confirm from '../../m-pack/src1/components/confirm/index.vue'
import ConfirmPlugin from '../../m-pack/src1/plugins/confirm/index.js'
import cookie from '../../m-pack/src1/tools/cookie/index.js'
import Countdown from '../../m-pack/src1/components/countdown/index.vue'
import Countup from '../../m-pack/src1/components/countup/index.vue'
import dateFormat from '../../m-pack/src1/tools/date/format.js'
import dateRange from '../../m-pack/src1/tools/date/range.js'
import Datetime from '../../m-pack/src1/components/datetime/index.vue'
import DatetimePlugin from '../../m-pack/src1/plugins/datetime/index.js'
import DatetimeRange from '../../m-pack/src1/components/datetime-range/index.vue'
import DatetimeView from '../../m-pack/src1/components/datetime-view/index.vue'
import debounce from '../../m-pack/src1/tools/debounce/index.js'
import Demobasic from '../../m-pack/src1/components/fullpage/DemoBasic.vue'
import Demoindex from '../../m-pack/src1/components/popover/DemoIndex.vue'
import DevicePlugin from '../../m-pack/src1/plugins/device/index.js'
import DevTip from '../../m-pack/src1/components/dev-tip/index.vue'
import Divider from '../../m-pack/src1/components/divider/index.vue'
import Drawer from '../../m-pack/src1/components/drawer/index.vue'
import Flexbox from '../../m-pack/src1/components/flexbox/flexbox.vue'
import FlexboxItem from '../../m-pack/src1/components/flexbox/flexbox-item.vue'
import Flow from '../../m-pack/src1/components/flow/flow.vue'
import FlowLine from '../../m-pack/src1/components/flow/flow-line.vue'
import FlowState from '../../m-pack/src1/components/flow/flow-state.vue'
import FormatTimeFilter from '../../m-pack/src1/filters/format-time.js'
import FormPreview from '../../m-pack/src1/components/form-preview/index.vue'
import FriendlyTimeFilter from '../../m-pack/src1/filters/friendly-time.js'
import Fullpage from '../../m-pack/src1/components/fullpage/index.vue'
import Grid from '../../m-pack/src1/components/grid/grid.vue'
import GridItem from '../../m-pack/src1/components/grid/grid-item.vue'
import Group from '../../m-pack/src1/components/group/index.vue'
import GroupTitle from '../../m-pack/src1/components/group-title/index.vue'
import Icon from '../../m-pack/src1/components/icon/index.vue'
import InlineCalendar from '../../m-pack/src1/components/inline-calendar/index.vue'
import InlineDesc from '../../m-pack/src1/components/inline-desc/index.vue'
import InlineLoading from '../../m-pack/src1/components/inline-loading/index.vue'
import InlineXNumber from '../../m-pack/src1/components/inline-x-number/index.vue'
import InlineXSwitch from '../../m-pack/src1/components/inline-x-switch/index.vue'
import InviewDirective from '../../m-pack/src1/directives/inview/index.js'
import Loading from '../../m-pack/src1/components/loading/index.vue'
import LoadingPlugin from '../../m-pack/src1/plugins/loading/index.js'
import LoadMore from '../../m-pack/src1/components/load-more/index.vue'
import LocalePlugin from '../../m-pack/src1/plugins/locale/index.js'
import Marquee from '../../m-pack/src1/components/marquee/marquee.vue'
import MarqueeItem from '../../m-pack/src1/components/marquee/marquee-item.vue'
import Masker from '../../m-pack/src1/components/masker/index.vue'
import md5 from '../../m-pack/src1/tools/md5/index.js'
import Msg from '../../m-pack/src1/components/msg/index.vue'
import Name2valueFilter from '../../m-pack/src1/filters/name2value.js'
import numberComma from '../../m-pack/src1/tools/number/comma.js'
import numberPad from '../../m-pack/src1/tools/number/pad.js'
import numberRandom from '../../m-pack/src1/tools/number/random.js'
import numberRange from '../../m-pack/src1/tools/number/range.js'
import NumberRoller from '../../m-pack/src1/components/number-roller/index.vue'
import Panel from '../../m-pack/src1/components/panel/index.vue'
import Picker from '../../m-pack/src1/components/picker/index.vue'
import Popover from '../../m-pack/src1/components/popover/index.vue'
import Popup from '../../m-pack/src1/components/popup/index.vue'
import PopupHeader from '../../m-pack/src1/components/popup-header/index.vue'
import PopupPicker from '../../m-pack/src1/components/popup-picker/index.vue'
import PopupRadio from '../../m-pack/src1/components/popup-radio/index.vue'
import Previewer from '../../m-pack/src1/components/previewer/index.vue'
import Qrcode from '../../m-pack/src1/components/qrcode/index.vue'
import querystring from '../../m-pack/src1/tools/querystring/index.js'
import Radio from '../../m-pack/src1/components/radio/index.vue'
import Range from '../../m-pack/src1/components/range/index.vue'
import Rater from '../../m-pack/src1/components/rater/index.vue'
import Scroller from '../../m-pack/src1/components/scroller/index.vue'
import Search from '../../m-pack/src1/components/search/index.vue'
import Selector from '../../m-pack/src1/components/selector/index.vue'
import Shake from '../../m-pack/src1/components/shake/index.vue'
import Spinner from '../../m-pack/src1/components/spinner/index.vue'
import Step from '../../m-pack/src1/components/step/step.vue'
import StepItem from '../../m-pack/src1/components/step/step-item.vue'
import Sticky from '../../m-pack/src1/components/sticky/index.vue'
import stringTrim from '../../m-pack/src1/tools/string/trim.js'
import Swipeout from '../../m-pack/src1/components/swipeout/swipeout.vue'
import SwipeoutButton from '../../m-pack/src1/components/swipeout/swipeout-button.vue'
import SwipeoutItem from '../../m-pack/src1/components/swipeout/swipeout-item.vue'
import Swiper from '../../m-pack/src1/components/swiper/swiper.vue'
import SwiperItem from '../../m-pack/src1/components/swiper/swiper-item.vue'
import Tab from '../../m-pack/src1/components/tab/tab.vue'
import Tabbar from '../../m-pack/src1/components/tabbar/tabbar.vue'
import TabbarItem from '../../m-pack/src1/components/tabbar/tabbar-item.vue'
import TabItem from '../../m-pack/src1/components/tab/tab-item.vue'
import throttle from '../../m-pack/src1/tools/throttle/index.js'
import Timeline from '../../m-pack/src1/components/timeline/timeline.vue'
import TimelineItem from '../../m-pack/src1/components/timeline/timeline-item.vue'
import Tip from '../../m-pack/src1/components/tip/index.vue'
import Toast from '../../m-pack/src1/components/toast/index.vue'
import ToastPlugin from '../../m-pack/src1/plugins/toast/index.js'
import TransferDom from '../../m-pack/src1/directives/transfer-dom/index.js'
import TransferDomDirective from '../../m-pack/src1/directives/transfer-dom/index.js'
import trim from '../../m-pack/src1/tools/string/trim'
import Value2nameFilter from '../../m-pack/src1/filters/value2name.js'
//import VArea from '../../m-pack/src1/components/v-chart/v-area.vue'
//import VAxis from '../../m-pack/src1/components/v-chart/v-axis.vue'
//import VBar from '../../m-pack/src1/components/v-chart/v-bar.vue'
//import VChart from '../../m-pack/src1/components/v-chart/v-chart.vue'
//import VGuide from '../../m-pack/src1/components/v-chart/v-guide.vue'
import Video from '../../m-pack/src1/components/video/index.vue'
import ViewBox from '../../m-pack/src1/components/view-box/index.vue'
/*import VLegend from '../../m-pack/src1/components/v-chart/v-legend.vue'
import VLine from '../../m-pack/src1/components/v-chart/v-line.vue'
import VPie from '../../m-pack/src1/components/v-chart/v-pie.vue'
import VPoint from '../../m-pack/src1/components/v-chart/v-point.vue'
import VScale from '../../m-pack/src1/components/v-chart/v-scale.vue'
import VTooltip from '../../m-pack/src1/components/v-chart/v-tooltip.vue'*/
import VuxComponentListData from '../../m-pack/src1/datas/vux_component_list.json'
import WechatEmotion from '../../m-pack/src1/components/wechat-emotion/index.vue'
import WechatPlugin from '../../m-pack/src1/plugins/wechat/index.js'
import WeekCalendar from '../../m-pack/src1/components/week-calendar/index.vue'
import WepayInput from '../../m-pack/src1/components/wepay-input/index.vue'
import XAddress from '../../m-pack/src1/components/x-address/index.vue'
import XButton from '../../m-pack/src1/components/x-button/index.vue'
import XCircle from '../../m-pack/src1/components/x-circle/index.vue'
import XDialog from '../../m-pack/src1/components/x-dialog/index.vue'
import XHeader from '../../m-pack/src1/components/x-header/index.vue'
import XHr from '../../m-pack/src1/components/x-hr/index.vue'
import XImg from '../../m-pack/src1/components/x-img/index.vue'
import XInput from '../../m-pack/src1/components/x-input/index.vue'
import XNumber from '../../m-pack/src1/components/x-number/index.vue'
import XProgress from '../../m-pack/src1/components/x-progress/index.vue'
import XSwitch from '../../m-pack/src1/components/x-switch/index.vue'
import XTable from '../../m-pack/src1/components/x-table/index.vue'
import XTextarea from '../../m-pack/src1/components/x-textarea/index.vue'

Vue.component("grid",Grid);
Vue.component("grid-item",GridItem);
Vue.component("group-title",GroupTitle);
Vue.component("mheader",mheader);
Vue.component("card",Card);
Vue.component("divider",Divider);
Vue.component("XDialog",XDialog);

//import { Group, Cell, DatetimePlugin, CloseDialogsPlugin, Plugin1, ConfigPlugin, BusPlugin, LocalePlugin, DevicePlugin, ToastPlugin, AlertPlugin, ConfirmPlugin, LoadingPlugin, WechatPlugin, AjaxPlugin, AppPlugin } from '../../m-pack/index'

// global VUX config
Vue.use(ConfigPlugin, {
    $layout: 'VIEW_BOX' // global config for VUX, since v2.5.12
})

// plugins
Vue.use(DevicePlugin)
Vue.use(ToastPlugin)
Vue.use(AlertPlugin)
Vue.use(ConfirmPlugin)
Vue.use(LoadingPlugin)
Vue.use(WechatPlugin)
Vue.use(AjaxPlugin)
Vue.use(BusPlugin)
Vue.use(DatetimePlugin)